const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    textSecondary: '#999',
    textBlue: '#4169E1',
    background: '#fff',
    backgroundLogin: '#f5f5f5',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    backgroundInput: '#FeFeFe',
    tabIconSelected: tintColorLight,
    shadow: '#000',
    buttonColorText: 'blackText',
    buttonColor: 'white',
    buttonOptionColor: 'white',
    buttonOptionColorActive: 'blue',
    buttonOptionColorText: 'blackText',
    buttonOptionColorTextActive: 'whiteText',
    buttonShadow: 'blackShadow',
  },
  dark: {
    text: '#000',
    textSecondary: '#999',
    textBlue: '#4169E1',
    background: '#fff',
    backgroundLogin: '#f5f5f5',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    backgroundInput: '#FeFeFe',
    tabIconSelected: tintColorLight,
    shadow: '#000',
    buttonColorText: 'blackText',
    buttonColor: 'white',
    buttonOptionColor: 'white',
    buttonOptionColorActive: 'blue',
    buttonOptionColorText: 'blackText',
    buttonOptionColorTextActive: 'whiteText',
    buttonShadow: 'blackShadow',
  },
};
